# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '93e19e2064cfe9e191b1ff3a10ca0dfc'
  config.secret_key = '5e839b98cf9da3ea23ec9c7cd7cbc6f1'
  config.default_from = 'thpcatshopping@gmail.com'

end
